# Generated by Django 5.1.4 on 2026-01-14 14:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankStatementUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='bank_statements/%Y/%m/%d/')),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('xlsx', 'Excel'), ('xls', 'Excel Legacy'), ('csv', 'CSV')], max_length=10)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('account_number', models.CharField(blank=True, max_length=50)),
                ('statement_period', models.CharField(blank=True, max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_statement_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bank Statement Upload',
                'verbose_name_plural': 'Bank Statement Uploads',
                'db_table': 'bank_statement_uploads',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='BankStatementAnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('features', models.JSONField(default=dict)),
                ('summary', models.JSONField(default=dict)),
                ('transactions', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('upload', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_result', to='bank_statement_analysis.bankstatementupload')),
            ],
            options={
                'verbose_name': 'Bank Statement Analysis Result',
                'verbose_name_plural': 'Bank Statement Analysis Results',
                'db_table': 'bank_statement_analysis_results',
                'ordering': ['-created_at'],
            },
        ),
    ]
