# Generated by Django 5.1.4 on 2026-01-14 14:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditReportUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='credit_reports/%Y/%m/%d/')),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('json', 'JSON')], max_length=10)),
                ('bureau_name', models.CharField(blank=True, choices=[('cibil', 'CIBIL'), ('experian', 'Experian'), ('equifax', 'Equifax'), ('crif', 'CRIF')], max_length=50)),
                ('report_date', models.DateField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_report_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Credit Report Upload',
                'verbose_name_plural': 'Credit Report Uploads',
                'db_table': 'credit_report_uploads',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='CreditReportAnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('features', models.JSONField(default=dict)),
                ('summary', models.JSONField(default=dict)),
                ('accounts', models.JSONField(default=list)),
                ('enquiries', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('upload', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_result', to='credit_report_analysis.creditreportupload')),
            ],
            options={
                'verbose_name': 'Credit Report Analysis Result',
                'verbose_name_plural': 'Credit Report Analysis Results',
                'db_table': 'credit_report_analysis_results',
                'ordering': ['-created_at'],
            },
        ),
    ]
