# Generated by Django 5.1.4 on 2026-01-14 14:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ITRUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='itr_uploads/%Y/%m/%d/')),
                ('file_type', models.CharField(choices=[('json', 'JSON'), ('pdf', 'PDF')], max_length=10)),
                ('assessment_year', models.CharField(blank=True, max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itr_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ITR Upload',
                'verbose_name_plural': 'ITR Uploads',
                'db_table': 'itr_uploads',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ITRAnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('features', models.JSONField(default=dict)),
                ('summary', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('upload', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_result', to='itr_analysis.itrupload')),
            ],
            options={
                'verbose_name': 'ITR Analysis Result',
                'verbose_name_plural': 'ITR Analysis Results',
                'db_table': 'itr_analysis_results',
                'ordering': ['-created_at'],
            },
        ),
    ]
