# Generated by Django 5.1.4 on 2026-01-14 15:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditScoreRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_score_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Credit Score Request',
                'verbose_name_plural': 'Credit Score Requests',
                'db_table': 'credit_score_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CreditScoreResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_score', models.IntegerField()),
                ('default_probability', models.FloatField()),
                ('risk_tier', models.CharField(max_length=50)),
                ('feature_importance', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='credit_scoring.creditscorerequest')),
            ],
            options={
                'verbose_name': 'Credit Score Result',
                'verbose_name_plural': 'Credit Score Results',
                'db_table': 'credit_score_results',
                'ordering': ['-created_at'],
            },
        ),
    ]
