"""Configuration module for Consumer Credit Scoring"""

from .feature_weights import CONSUMER_FEATURE_WEIGHTS, FEATURE_CATEGORIES, CATEGORY_WEIGHTS
from .constants import (
    SCORE_RANGE,
    CONSUMER_RISK_TIERS,
    EDUCATION_LEVELS,
    EMPLOYMENT_TYPES,
    SPENDING_PERSONALITIES
)
from .hyperparameters import DEFAULT_CONSUMER_LGB_PARAMS, OPTUNA_CONFIG

__all__ = [
    'CONSUMER_FEATURE_WEIGHTS',
    'FEATURE_CATEGORIES',
    'CATEGORY_WEIGHTS',
    'SCORE_RANGE',
    'CONSUMER_RISK_TIERS',
    'EDUCATION_LEVELS',
    'EMPLOYMENT_TYPES',
    'SPENDING_PERSONALITIES',
    'DEFAULT_CONSUMER_LGB_PARAMS',
    'OPTUNA_CONFIG'
]


