# Generated by Django 5.1.4 on 2026-01-14 14:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='documents/%Y/%m/%d/')),
                ('document_type', models.CharField(choices=[('aadhaar', 'Aadhaar Card'), ('pan', 'PAN Card'), ('voter_id', 'Voter ID'), ('passport', 'Passport'), ('driving_license', 'Driving License'), ('user_photo', 'User Photo'), ('other', 'Other')], max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document Upload',
                'verbose_name_plural': 'Document Uploads',
                'db_table': 'document_uploads',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='FaceMatchRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('aadhaar_photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='face_match_as_aadhaar', to='ocr_analysis.documentupload')),
                ('pan_photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='face_match_as_pan', to='ocr_analysis.documentupload')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_match_requests', to=settings.AUTH_USER_MODEL)),
                ('user_photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_match_as_user_photo', to='ocr_analysis.documentupload')),
                ('voter_id_photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='face_match_as_voter_id', to='ocr_analysis.documentupload')),
            ],
            options={
                'verbose_name': 'Face Match Request',
                'verbose_name_plural': 'Face Match Requests',
                'db_table': 'face_match_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FaceMatchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_verdict', models.CharField(max_length=50)),
                ('verdict_description', models.TextField()),
                ('results', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='ocr_analysis.facematchrequest')),
            ],
            options={
                'verbose_name': 'Face Match Result',
                'verbose_name_plural': 'Face Match Results',
                'db_table': 'face_match_results',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OCRResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extracted_data', models.JSONField(default=dict)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ocr_result', to='ocr_analysis.documentupload')),
            ],
            options={
                'verbose_name': 'OCR Result',
                'verbose_name_plural': 'OCR Results',
                'db_table': 'ocr_results',
                'ordering': ['-created_at'],
            },
        ),
    ]
